---
title: "Max Farrell"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.



## Publications

Publications scraped from <https://scholar.google.com/citations?user=8IOC1BMAAAAJ&hl=en>.


```{r scraping_scholar, echo=FALSE, warning=FALSE, message=FALSE}

# based on: https://peder.quarto.pub/blog/posts/scraping_scholar/
library(kableExtra)
library(formattable)
library(scholar)
library(dplyr)
library(ggpubr)

author_id <- "8IOC1BMAAAAJ"
pubs <- scholar::get_publications(author_id) 

```

```{r pubs_table, echo=FALSE}

# Prepare a data frame for the table
pubs_df <-
      pubs %>%
        mutate(full_citation = paste0(
          author,
          " (", year, "). ",
          title, ". ",
          journal, ". ",
          number, ". "
        )) %>%
        arrange(-year, title)


# names(pubs_df)
# pubs_df$cites

# # Prepare a data frame for the table
# pubs_df <-
#   data.frame(
#     # For each article, create a character string including author, title, year, journal and page number, issue etc
#     Information =
#       pubs %>%
#         mutate(full_citation = paste0(
#           author,
#           " (", year, "). ",
#           title, ". ",
#           journal, ". ",
#           number, ". "
#         )) %>%
#         arrange(year, title) %>%
#         pull(full_citation),
#     # Pull the number of citations
#     citations =
#       pubs %>% arrange(-year, title) %>% pull(cites),
#     # Pull the publication ID (may be handy for later joining with other metrics)
#     pubid =
#       pubs %>% arrange(year, title) %>% pull(pubid)
#   )

# names(pubs_df)
# View(pubs_df)

# We use formattable::color_bar to assign a color to the bars reflecting the relative number of citations
pubs_df$citations <- formattable::color_bar("#ffd38b")(pubs_df$cites)

# names(pubs_df)

# Create the table
pubs_df %>% select(-c(cid, pubid, cites)) %>% unique() %>%
  kable("html", escape = F, html_font = "Roboto") %>%
  kable_paper() %>%
  # Specify width of the citations bar cells
  # column_spec(2, width = "4cm") %>%
  kable_styling(bootstrap_options = "striped", font_size = 14) %>%
  scroll_box(width = "1200px", height = "800px") %>%
  footnote("Shows only peer-reviewed articles and pre-prints") 

```